### ISSUE TITLE
is there a plan to publish docker images?

### ISSUE THREAD

**Issue by vishwanathj** [yoheimuta/protolint#92]

**Comment by yoheimuta** [comment]
@vishwanathj Thank you for your suggestion!

I didn't expect to publish a docker image.
However, that sounds convenient so I'd like it.

**Comment by yoheimuta** [comment]
I will support this in a bit.

**Comment by vishwanathj** [comment]
@yoheimuta Thanks

**Comment by yoheimuta** [comment]
@vishwanathj I shipped the Docker image. 
Please check it out whenever you have time.

- ref. https://github.com/yoheimuta/protolint#use-the-maintained-docker-image

**Comment by vishwanathj** [comment]
@vishwanathj Thanks for making this happen, I tested it and it works awesome.
What would be another helpful thing would if the git releases have a corresponding published docker images.

**Comment by yoheimuta** [comment]
@vishwanathj I missed mentioning the version releases.
protolint is also supporting it, which means automatically building a corresponding image as the GitHub Releases. 

I just didn't ship the image yet because there were not many updates.

That said, for confirmation, I just released v0.20.1 a while ago.

- https://hub.docker.com/layers/yoheimuta/protolint/v0.20.1/images/sha256-0d63314d44a91d6643cb2c21c349b990bee6f766e95d9f7b6eae2d134a330a6d

**Comment by vishwanathj** [comment]
> @vishwanathj I missed mentioning the version releases.
> protolint is also supporting it, which means automatically building a corresponding image as the GitHub Releases.
> 
> I just didn't ship the image yet because there were not many updates.
> 
> That said, for confirmation, I just released v0.20.1 a while ago.
> 
> * https://hub.docker.com/layers/yoheimuta/protolint/v0.20.1/images/sha256-0d63314d44a91d6643cb2c21c349b990bee6f766e95d9f7b6eae2d134a330a6d

Awesome, thanks a bunch
